apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-base
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
  interval: 5m
  path: "./apps/base"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
