apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure-all
  namespace: flux-system
spec:
  interval: 5m
  path: "./infrastructure"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prod-apps
  namespace: flux-system
spec:
  interval: 5m
  path: "./apps/prod"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: staging-apps
  namespace: flux-system
spec:
  interval: 5m
  path: "./apps/staging"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client