apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastucture
  namespace: flux-system
spec:
  interval: 5m
  path: "./infrastructure/kustomizations"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prod-apps
  namespace: flux-system
spec:
  dependsOn: 
    - name: infrastucture-apps
  interval: 5m
  path: "./apps/prod"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client