apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  interval: 5m
  path: "./infrastructure/namespace"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastucture-apps
  namespace: flux-system
spec:
  dependsOn:
    - name: namespaces
    - name: infrastucture-configs
  interval: 5m
  path: "./infrastructure/apps"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastucture-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: namespaces
  interval: 5m
  path: "./infrastructure/configs"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastucture-repos
  namespace: flux-system
spec:
  interval: 5m
  path: "./infrastructure/repos"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client