apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: us-east-apps
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
  interval: 5m
  path: "./apps/us-east"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
