apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: eu-west-apps
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
  interval: 5m
  path: "./apps/eu-west"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
