apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mablab-acr
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgCRI9Cj3rvS4701Ro2n1lv0SLmv/exkKsADCYpCxgEHn9pRxQzQKsyroaUxBWOdKd3AKy/Iod/nz7JV0I19GSk4MnoHrfhzfIytwQmYkp6DUotkSqFkPrJtEpj4EUNV00W+7KxGdrIaoPjm/9rTiIqy/36HdlUyrZRC2nsyVwbQTfQXSvtOOIjVEIN/UYheqIQCTz8msTAxrax5YGKlIpqcJEfLDdJvRBgHRwRzJ+wn78cr+i749TsU5THK2HMlLnLlEsdESs1gDx8NInF7syNB27ta2L5NfO6DZ1gBNrqkR8c67WlygdR4ju4kWNqzPLrubrVg6ksw4NUiuKf6pDsTlgl4LTLSMP22FaH9OD02rsVnpfN65hrLAi5NY5Nv4XrqosTJPPtyLeXRgdooflgE1ysQZEcsU5IAt4WkMwYlbmxH7UESb/1Te9i24k4VZP0qKsV6wyC9+jDjmacMlVVQWNpkDs6hgZD+kETSTGEnk9kTXgMygF2AQkusXE98M/pm300RkKwC35QTd67/P3135XEdcbYY6fhJ1S/K55GYZqfZvgiIgCICTXepYnNqLQeap1qafpb2FTaGAx/kVAlw4FOAWdmTtF/63HE7HXx/9Sr9CXPO0uMKUmwY9ChvUF+M6H7ATPuWP53INornCOciYlF74voaZ7QzI4OuIEbqnq8Zsn9/ZrGRusRrxqX/vVUz8BdQflfTRaHuE6Q+wtqwQQycv5ABVSCflc/gh8CcPnRuaKQxNCmDgfz2FycOyhJETKu7vMP1F9xYZ0XoAB3prm9Mb31X01MQK/HYkKKSa471x0qzOJl2XmKEHpWgXuUwoC1TDMc4jKHkzg1HlhwpYnwrSLGeCCsqcc1qWed7j5iA5xz8YWMLcZC0r3WVtErGkXc6dEEJMyFNHr02Wcy5mTy7RnJNmn6S/OZdliFv32CaiipHlROt2T2qlh5/dMEovdV2H2QN8YQY3O4W64hTvnQBDs3VxTni1aEbRNCLktmJqJkb/GFUAdYXwaCFM6mz
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: mablab-acr
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
