apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: staging-webserver
  namespace: flux-system
spec:
  targetNamespace: default
  interval: 5m
  path: "./apps/base"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  patches:
    - patch: |
        - op: replace
          path: /metadata
          value:
            name: staging-webserver
            namespace: default
      target:
        kind: Deployment
        name: nginx-webserver
        namespace: default
