apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paymentserver
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: paymentserver
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: oci-mablab
        namespace: flux-system
      interval: 1m
  values:
    controller:
      replicas: 3
    image:
      repository: nginx
      tag: latest
    service:
      main:
        ports:
          http:
            port: 8080
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
