apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: base-paymentserver
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: paymentserver
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: mablab-oci
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: nginx
      tag: stable