apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealedsecret
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: sealed-secrets
      version: 2.7.6
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
      interval: 1m
  values:
